version: "3.8"
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - OLLAMA_MODELS=${OLLAMA_MODELS}
      - OLLAMA_API_ENDPOINT=http://host.docker.internal:11434

      - OPENAI_MODELS=${OPENAI_MODELS}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_ENDPOINT=${OPENAI_API_ENDPOINT}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_ENDPOINT=http://backend:8000
    command: ["streamlit", "run", "app.py"]

volumes:
  db-data:
