version: "3.8"
services:
  ollama:
    build: ./ollama
    ports:
      - "${OLLAMA_PORT}:11434"
    env_file:
      - .env # This will pass all .env variables into the container

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - ollama
    environment:
      - OLLAMA_API_ENDPOINT=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_ENDPOINT=${OPENAI_API_ENDPOINT}
      - OPENAI_MODELS=${OPENAI_MODELS}
      - OLLAMA_MODELS=${OLLAMA_MODELS}

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - BACKEND_ENDPOINT=http://backend:8000
    command: ["streamlit", "run", "app.py"]
