version: "3.8"
services:
  db:
    image: postgres:16.2-bullseye
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./db/scripts:/scripts
      - ./db/snapshot:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"

  db-dashboard:
    image: dpage/pgadmin4
    container_name: db-dashboard
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${DB_DASHBOARD_PORT}:80"
    volumes:
      - db-dashboard-data:/var/lib/pgadmin

  ollama:
    build: ./ollama
    container_name: ollama
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${OLLAMA_PORT}:11434"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_APP_USER}:${POSTGRES_APP_PASSWORD}@${POSTGRES_DB_HOST}:5432/${POSTGRES_DB}

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend:/app
      - ./logs/backend:/app/logs
    depends_on:
      - db
      - ollama
    env_file:
      - .env
    environment:
      - APP_CONTEXT=backend
      - OLLAMA_API_ENDPOINT=http://ollama:11434

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:8501"
    volumes:
      - ./frontend:/app
      - ./logs/frontend:/app/logs
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - APP_CONTEXT=frontend
      - BACKEND_ENDPOINT=http://backend:8000
    command: ["streamlit", "run", "app.py"]

volumes:
  db-data:
  db-dashboard-data:
