# Dockerfile for db service

# Use the official PostgreSQL image
#FROM postgres:16-alpine
# Use the official PostgreSQL image
FROM postgres:16.2-bullseye

# Set environment variables
#ENV POSTGRES_DB cs5934_postgresqldb
#ENV POSTGRES_USER cs5934_dbuser
#ENV POSTGRES_PASSWORD cs5934_pass

# Copy SQL scripts into the container
COPY /scripts/create_schema.sql /docker-entrypoint-initdb.d/
COPY /scripts/create_tables.sql /docker-entrypoint-initdb.d/
COPY /scripts/insert_initial_data.sql /docker-entrypoint-initdb.d/

# Expose port 5432
EXPOSE 5432

# Set environment variables
ENV POSTGRES_DB cs5934_postgresqldb
ENV POSTGRES_USER cs5934_dbuser
ENV POSTGRES_PASSWORD cs5934_pass


# Copy entrypoint script into the container
# COPY entrypoint.sh /usr/local/bin/
# RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
# ENTRYPOINT ["entrypoint.sh"]